POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "420skun@gmail.com",
    "password": "HYui92",
    "first_name": "abcnoń          ",
    "last_name": "           ś€€ó 88883"
}

###

GET http://localhost:3000/protected
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJlc3RAdGVzdC5jb20iLCJyb2xlIjoxLCJpYXQiOjE3MjI4NjgxMTIsImV4cCI6MTcyMjg3MTcxMn0.OBoP3gYuJhUdpqSuYkKnEsCiIBCqJc8_Z1D0dLioeCw

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "rest@test.com",
    "password": "abcdef"
}

###

GET http://localhost:3000/api/auth/qr?id=1

###

GET http://localhost:3000
