###

GET http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiI0MjBza3VuQGdtYWlsLmNvbSIsInJvbGUiOjEsImZpcnN0X25hbWUiOm51bGwsImlhdCI6MTcyMzUxMTMyNSwiZXhwIjoxNzU1MDQ3MzI1fQ.cnHTATElzZiysuISkkJYa-FPExftIhoLqtxF5wIKT2w

###

DELETE http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImVtYWlsIjoiNDIwc2t1bkBnbWFpbC5jb20iLCJyb2xlIjoxLCJmaXJzdF9uYW1lIjpudWxsLCJpYXQiOjE3MjM1NzI2NzAsImV4cCI6MTc1NTEwODY3MH0.gu64AEK6QsDrMtd90PT38cJjlKQlBjtMRQt38ncBznI

###

POST http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImVtYWlsIjoiNDIwc2t1bkBnbWFpbC5jb20iLCJyb2xlIjoxLCJmaXJzdF9uYW1lIjpudWxsLCJpYXQiOjE3MjM1NzI2NzAsImV4cCI6MTc1NTEwODY3MH0.gu64AEK6QsDrMtd90PT38cJjlKQlBjtMRQt38ncBznI
Content-Type: application/json

{
    "first_name": "patientfirst",
    "last_name": "patientlast"
}

###

GET http://localhost:3000/api/user/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiI0MjBza3VuQGdtYWlsLmNvbSIsInJvbGUiOjEsImZpcnN0X25hbWUiOm51bGwsImlhdCI6MTcyMzUxMTMyNSwiZXhwIjoxNzU1MDQ3MzI1fQ.cnHTATElzZiysuISkkJYa-FPExftIhoLqtxF5wIKT2w