###

GET http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiI0MjBza3VuQGdtYWlsLmNvbSIsInJvbGUiOjEsImZpcnN0X25hbWUiOm51bGwsImlhdCI6MTcyMzUxMTMyNSwiZXhwIjoxNzU1MDQ3MzI1fQ.cnHTATElzZiysuISkkJYa-FPExftIhoLqtxF5wIKT2w

###

POST http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiI0MjBza3VuQGdtYWlsLmNvbSIsInJvbGUiOjEsImZpcnN0X25hbWUiOm51bGwsImlhdCI6MTcyMzUxMTMyNSwiZXhwIjoxNzU1MDQ3MzI1fQ.cnHTATElzZiysuISkkJYa-FPExftIhoLqtxF5wIKT2w
Content-Type: application/json

{
    "first_name": "patientfirst",
    "last_name": "patientlast"
}

###

GET http://localhost:3000/api/user/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiI0MjBza3VuQGdtYWlsLmNvbSIsInJvbGUiOjEsImZpcnN0X25hbWUiOm51bGwsImlhdCI6MTcyMzUxMTMyNSwiZXhwIjoxNzU1MDQ3MzI1fQ.cnHTATElzZiysuISkkJYa-FPExftIhoLqtxF5wIKT2w